stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  script:
    - echo "Building the code..."

test_job:
  stage: test
  script:
    - echo "Running tests..."

deploy_job:
  stage: deploy
  script:
    - echo "Deploying the code..."
